defmodule Breakaway.Repo.Migrations.RememberLastPosition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :last_space_id, :uuid
      add :last_x, :float
      add :last_y, :float
    end
  end

  def down do
    alter table(:users) do
      remove :last_y
      remove :last_x
      remove :last_space_id
    end
  end
end
