defmodule Breakaway.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:props, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :x, :bigint, null: false
      add :y, :bigint, null: false
      add :solid, :boolean, null: false, default: true
      add :space_id, :uuid, null: false
    end

    create table(:spaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:props) do
      modify :space_id,
             references(:spaces,
               column: :id,
               name: "props_space_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:spaces) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :width, :bigint, null: false
      add :height, :bigint, null: false
      add :spawn_x, :bigint, null: false, default: 1
      add :spawn_y, :bigint, null: false, default: 1
      add :ground, {:array, :bigint}, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:spaces, [:slug], name: "spaces_unique_slug_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:user_identities, primary_key: false) do
      add :refresh_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :access_token, :text
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid
    end

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_identities) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_identities_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      add :discord_id, :text, null: false
      add :discord_username, :text, null: false
      add :display_name, :text, null: false
      add :discord_avatar, :text
      add :email, :citext
      add :status_message, :text
      add :avatar_palette, :bigint, null: false, default: 0
      add :discord_access_token, :text
      add :discord_refresh_token, :text
      add :discord_token_expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:discord_id], name: "users_unique_discord_id_index")

    create table(:zones, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :kind, :text, null: false, default: "meeting"
      add :x, :bigint, null: false
      add :y, :bigint, null: false
      add :width, :bigint, null: false
      add :height, :bigint, null: false
      add :capacity, :bigint
      add :accent, :text, default: "#6f8fd6"
      add :discord_guild_id, :text
      add :discord_channel_id, :text
      add :discord_channel_name, :text
      add :auto_move, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :space_id,
          references(:spaces,
            column: :id,
            name: "zones_space_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:zones, [:space_id, :slug], name: "zones_unique_slug_per_space_index")
  end

  def down do
    drop constraint(:zones, "zones_space_id_fkey")

    drop_if_exists unique_index(:zones, [:space_id, :slug],
                     name: "zones_unique_slug_per_space_index"
                   )

    drop table(:zones)

    drop_if_exists unique_index(:users, [:discord_id], name: "users_unique_discord_id_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :discord_token_expires_at
      remove :discord_refresh_token
      remove :discord_access_token
      remove :avatar_palette
      remove :status_message
      remove :email
      remove :discord_avatar
      remove :display_name
      remove :discord_username
      remove :discord_id
    end

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    alter table(:user_identities) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    drop table(:user_identities)

    drop table(:tokens)

    drop_if_exists unique_index(:spaces, [:slug], name: "spaces_unique_slug_index")

    alter table(:spaces) do
      remove :updated_at
      remove :inserted_at
      remove :ground
      remove :spawn_y
      remove :spawn_x
      remove :height
      remove :width
      remove :slug
      remove :name
    end

    drop constraint(:props, "props_space_id_fkey")

    alter table(:props) do
      modify :space_id, :uuid
    end

    drop table(:spaces)

    drop table(:props)
  end
end
