defmodule Breakaway.Repo.Migrations.AddPropFacing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:props) do
      add :facing, :text, null: false, default: "down"
    end
  end

  def down do
    alter table(:props) do
      remove :facing
    end
  end
end
